name: "publish package to npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to latest version
        with:
          node-version: 20.x 

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
